# Generated by Django 3.2.16 on 2022-12-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Author', 'Author'), ('Reader', 'Reader')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
