# Generated by Django 3.2.16 on 2022-12-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
